CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Notes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Subject" character varying(80) NOT NULL,
    "Content" text NULL,
    "IsPublic" boolean NOT NULL,
    "Created" timestamp without time zone NOT NULL,
    "Updated" timestamp without time zone NOT NULL,
    "Deleted" boolean NOT NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
);

CREATE TABLE "Tags" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Label" character varying(30) NOT NULL,
    "NoteCount" integer NOT NULL,
    "LastUsed" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_Tags_Label" UNIQUE ("Label")
);

CREATE TABLE "NoteTags" (
    "NoteId" integer NOT NULL,
    "Label" character varying(30) NOT NULL,
    CONSTRAINT "PK_NoteTags" PRIMARY KEY ("NoteId", "Label"),
    CONSTRAINT "FK_NoteTags_Notes_NoteId" FOREIGN KEY ("NoteId") REFERENCES "Notes" ("Id") ON DELETE CASCADE
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201008050847_InitialSchema', '3.1.8');

