CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Files" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(1000) NOT NULL,
    "Version" integer NOT NULL,
    "ContentType" character varying(255) NULL,
    "Size" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Updated" timestamp with time zone NOT NULL,
    "IsFolder" boolean NOT NULL,
    "ParentId" integer NULL,
    "AccessCount" integer NOT NULL,
    "IsFavorite" boolean NOT NULL,
    "IsPublic" boolean NOT NULL,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Files_Files_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Files" ("Id")
);

CREATE TABLE "Notes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Subject" character varying(80) NOT NULL,
    "Content" text NULL,
    "Created" timestamp with time zone NOT NULL,
    "Updated" timestamp with time zone NOT NULL,
    "Published" timestamp with time zone NULL,
    "IsPinned" boolean NOT NULL,
    "ViewCount" integer NOT NULL,
    "Summary" text NULL,
    "IsBlog" boolean NOT NULL DEFAULT FALSE,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY ("Id")
);

CREATE TABLE "FileHistories" (
    "FileId" integer NOT NULL,
    "Version" integer NOT NULL,
    "Name" character varying(1000) NOT NULL,
    "ContentType" character varying(255) NULL,
    "Size" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Updated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FileHistories" PRIMARY KEY ("FileId", "Version"),
    CONSTRAINT "FK_FileHistories_Files_FileId" FOREIGN KEY ("FileId") REFERENCES "Files" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Files_ParentId" ON "Files" ("ParentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221008233114_InitialSchema', '6.0.9');

COMMIT;

